//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace regtr
{
    using System;
    using System.Collections.Generic;
    
    public partial class auth
    {
        public auth()
        {
            this.client = new HashSet<client>();
        }
    
        public int user_id { get; set; }
        public string login { get; set; }
        public string pass { get; set; }
        public bool roll { get; set; }
    
        public virtual ICollection<client> client { get; set; }
    }
}
