//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace regtr
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public client()
        {
            this.prodaja = new HashSet<prodaja>();
        }
    
        public int client_id { get; set; }
        public string name { get; set; }
        public string lastname { get; set; }
        public string phone { get; set; }
        public string adress { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual auth auth { get; set; }
        public virtual ICollection<prodaja> prodaja { get; set; }
    }
}
