//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace regtr
{
    using System;
    using System.Collections.Generic;
    
    public partial class items
    {
        public items()
        {
            this.prodaja = new HashSet<prodaja>();
        }
    
        public int item_id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string category { get; set; }
        public byte[] image { get; set; }
        public string color { get; set; }
        public string size { get; set; }
        public string nalichie { get; set; }
        public decimal cost { get; set; }
    
        public virtual ICollection<prodaja> prodaja { get; set; }
    }
}
