//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace regtr
{
    using System;
    using System.Collections.Generic;
    
    public partial class prodaja
    {
        public int prodaja_id { get; set; }
        public int client_id { get; set; }
        public int items_id { get; set; }
        public Nullable<decimal> summa { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public decimal cost { get; set; }
    
        public virtual client client { get; set; }
        public virtual items items { get; set; }
    }
}
